ALTER TABLE products ADD COLUMN IF NOT EXISTS cfop TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS csosn TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS cst TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS pis_cst TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS cofins_cst TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS icms_rate DECIMAL(5,2);
